name: "build-dev"

on:
  push: 
    branches:
      - dev
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Debug
      artifact-name: lancache-tdns-app-${{ github.ref_name }}