# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build TechnitiumLibrary.Net
      working-directory: ./TechnitiumLibrary
      run: dotnet build ./TechnitiumLibrary.Net -c Release
    - name: Build DnsServerCore.ApplicationCommon
      working-directory: ./DnsServer
      run: dotnet build ./DnsServerCore.ApplicationCommon
    - name: Restore dependencies
      working-directory: ./LANCacheApp
      run: dotnet restore
    - name: Build LANCacheApp
      working-directory: ./LANCacheApp
      run: dotnet build --no-restore -c Release
    - name: Test
      working-directory: ./LANCacheApp
      run: dotnet test --no-build --verbosity normal
    - name: List Release Files
      run: ls LANCacheApp/bin/Release/
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lancache-tdns-app
        path: LANCacheApp/bin/Release/
        if-no-files-found: error