# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Project

on:
  workflow_call: 
    inputs:
      configuration:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build TechnitiumLibrary.Net
      working-directory: ./TechnitiumLibrary
      run: dotnet build ./TechnitiumLibrary.Net -c Release
    - name: Build DnsServerCore.ApplicationCommon
      working-directory: ./DnsServer
      run: dotnet build ./DnsServerCore.ApplicationCommon -c Release
    - name: Restore dependencies
      working-directory: ./LANCacheApp
      run: dotnet restore
    - name: Build LANCacheApp
      working-directory: ./LANCacheApp
      run: dotnet build --no-restore -c ${{ inputs.configuration }}
    - name: Test
      working-directory: ./LANCacheApp
      run: dotnet test --no-build --verbosity normal
    - name: List Release Files
      run: ls LANCacheApp/bin/${{ inputs.configuration }}/
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: LANCacheApp/bin/${{ inputs.configuration }}/
        if-no-files-found: error
